### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by SyrianSpock** [SyrianSpock/nanocopter-autopilot#1]
[Schematics](https://github.com/SyrianSpock/nanocopter/blob/master/speedy.pdf)

**Comment by msplr** [comment]
The BOOT pin configuration is wrong. On power-on it will only boot into the ST-bootloader where it will wait forever for a firmware upgrade.
you have two options:
- add a button/jumper at BOOT0 to VCC with a pulldown.
- hardwire BOOT0 to GND and make use of the ST-bootloader by jumping to it from software. (as it is done in the INS-board form @Stapelzeiger)

Another possible issue is the following (from AN2606):

> - If DFU (USB FS Device) is used to connect to the bootloader:
>   the USART1_RX (PA10), USART3_RX (PC11 and PB11) and CAN2_RX (PB05) pins have to
>   be kept at a high or low level and must not be left floating during the detection phase.

At PB11 and PB5 you might have to add pulldown resistors. (PA10 and PC11 already pulled up/down)

**Comment by SyrianSpock** [comment]
@nuft Thanks for noticing. 

> The BOOT pin configuration is wrong. On power-on it will only boot into the ST-bootloader where it will wait forever for a firmware upgrade.
> - add a button/jumper at BOOT0 to VCC with a pulldown.
> - hardwire BOOT0 to GND and make use of the ST-bootloader by jumping to it from software. (as it is done in the INS-board form @Stapelzeiger)

I think I'll add a button.

> At PB11 and PB5 you might have to add pulldown resistors. (PA10 and PC11 already pulled up/down)

I'll fix that now.

**Comment by msplr** [comment]
There is no need for a second quartz at the radio module.
You can connect the clock output from the STM32 MCO1/MCO2 pin (PA8/PC9) to the nRF's XC1.
(See nRF24L01+ Product Specification, section 10.3 "nRF24L01+ crystal sharing with an MCU" for more information)

**Comment by msplr** [comment]
the SD power supply is not finished. (SD_VCC and SD_PWR_EN aren't connected)

**Comment by msplr** [comment]
> There might be a DMA stream conflict (See table in STM32F4 Reference Manual, 10.3.3 Channel selection)
> possible DMA streams:
> - SPI1 RX: 0 2
> - SPI1 TX: 3 5
> - SPI2 RX: 3
> - SPI2 TX: 4
> - I2C1 RX: 0 5
> - I2C1 TX: 6 7
> - SDIO: 3 6
> - ADC1: 0 4
> - ADC2: 2 3
> - ADC3: 0 1
> 
> There is no possible solution without omitting the ADCs. ChibiHAL uses DMA for its STM32 drivers. Therefore, if you want to pass on using DMA for a communication interface you need to write a driver yourself. On the other hand, I don't know if the ADC drivers use DMA, so there might be a solution to this.
> An option might be using ADC3 with stream 1. (which changing pins for CURRENT_BAT_SENSE and VOLTAGE_BAT_SENSE)

Edit: sorry, I confused DMA1 and DMA2 settings. I have to recheck for conflicts
Edit2:
**DMA1**
SPI2 RX: 3
SPI2 TX: 4
I2C1 RX: 0 5
I2C1 TX: 6 7
**DMA2**
ADC1: 0 4
ADC2: 2 3
SPI1 RX: 0 2
SPI1 TX: 3 5
SDIO: 3 6
-> _No_ DMA conflict

**Comment by msplr** [comment]
> All motors PWM is wired on Timer 1 Enable pins are on GPIO

This comment in the schematic is not correct.
MOTOR 3 and 4 are using TIM3 or TIM8

**Comment by msplr** [comment]
Are all the pullups at the SD data lines really necessary?

**Comment by SyrianSpock** [comment]
> Are all the pullups at the SD data lines really necessary?

According to [AN10911 from NXP](http://www.nxp.com/documents/application_note/AN10911.pdf) (pages 17, 18) yes.
Although not on the clock line and Data3.

> This comment in the schematic is not correct.
> MOTOR 3 and 4 are using TIM3 or TIM8

Good catch. This became wrong when I had to free PA11 for USB.

> -> No DMA conflict

Didn't even think to check that. Thanks.

> the SD power supply is not finished. (SD_VCC and SD_PWR_EN aren't connected)

That's what happens when you remove the SD card and revert the commit 5 months later without double checking the wiring. Fixing it.

> There is no need for a second quartz at the radio module.
> You can connect the clock output from the STM32 MCO1/MCO2 pin (PA8/PC9) to the nRF's XC1.
> (See nRF24L01+ Product Specification, section 10.3 "nRF24L01+ crystal sharing with an MCU" for more information)

Nice. Getting rid of the second quartz then.

**Comment by SyrianSpock** [comment]
@nuft From AN2606

> If DFU (USB FS Device) is used to connect to the bootloader: the USART1_RX (PA10), USART3_RX (PC11 and PB11) and CAN2_RX (PB05) pins have to be kept at a high or low level and must not be left floating during the detection phase.

It only concerns STM32F1 family, am I wrong ?

**Comment by msplr** [comment]
> It only concerns STM32F1 family, am I wrong ?

No, this was in the section about the STM32F4, but apparently I was referencing an old version (Rev 14).

In the more recent [AN2606 Rev 25](http://www.st.com/web/en/resource/technical/document/application_note/CD00167594.pdf) they removed the above comment, but they start talking about different bootloader verisions.

For the STM32F405RG you have to look at section 25.1 "Bootloader V3.x" which supports USART1 (PA10), USART3 (PB11 and PC11), CAN2 (PB5) and USB DFU. 
I think the CAN RX pin can safely be left floating, since it is quite improbable that a valid CAN frame is detected. But USART Rx pins should be pulled to a defined state.

Edit: 
for STM32F40xxx devices there exist two different bootloader versions, to find out which one is used you have to find this small note:

> Note: The bootloader version V9.x is only embedded in STM32F405xx/415xx WCSP90 package devices.

Dear ST, why does this have to be so complicated?
